services:
  # Using existing authentik-main PostgreSQL and Redis
  server:
    command: server
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__PORT: 5435
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_REDIS__HOST: authentik-main-redis-1
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    # Use the source-built image
    image: authentik-source:latest
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    volumes:
    - ./media:/media
    - ./custom-templates:/templates
    networks:
      - authentik-main_default
    external_links:
      - authentik-main-redis-1:redis
  worker:
    command: worker
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__PORT: 5435
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_REDIS__HOST: authentik-main-redis-1
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    # Use the source-built image
    image: authentik-source:latest
    restart: unless-stopped
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./media:/media
    - ./certs:/certs
    - ./custom-templates:/templates
    networks:
      - authentik-main_default
    external_links:
      - authentik-main-redis-1:redis

networks:
  authentik-main_default:
    external: true